#!/usr/bin/env bash
# forge pipeline — deliver: branch, commit, push, PR
# Generated by: forge init
# Uses bd (steveyegge/beads) for task tracking
set -euo pipefail

FORGE_DIR=".forge"
PROMPTS_DIR="${FORGE_DIR}/pipeline"

TASK_ID="${1:-}"
PR_BODY_FILE="${2:-}"

if [[ -z "$TASK_ID" ]]; then
  echo '{"error":"Usage: deliver.sh <task-id> [pr-body-file]"}' >&2
  exit 1
fi

# --- Read task state from bd ---

TASK_JSON=$(bd show "$TASK_ID" --json 2>/dev/null)

# bd show --json may return an array [{...}] or object {...} — normalize to object
bd_field() {
  echo "$TASK_JSON" | jq -r "if type == \"array\" then .[0].${1} else .${1} end // empty"
}

TITLE=$(bd_field "title")
TITLE="${TITLE:-untitled}"
DESCRIPTION=$(bd_field "description")

# Extract tier and mode from labels
TIER=$(echo "$TASK_JSON" | jq -r 'if type == "array" then .[0].labels[]? else .labels[]? end // empty' | grep "^tier:" | head -1 | sed 's/^tier://')
TIER="${TIER:-T1}"
MODE=$(echo "$TASK_JSON" | jq -r 'if type == "array" then .[0].labels[]? else .labels[]? end // empty' | grep "^mode:" | head -1 | sed 's/^mode://')
MODE="${MODE:-normal}"

# Detect modified files from git
MODIFIED_FILES=$(git diff --name-only HEAD 2>/dev/null || true)
if [[ -z "$MODIFIED_FILES" ]]; then
  MODIFIED_FILES=$(git diff --cached --name-only 2>/dev/null || true)
fi
if [[ -z "$MODIFIED_FILES" ]]; then
  MODIFIED_FILES=$(git status --porcelain | grep -v '^\?' | awk '{print $2}')
fi

if [[ -z "$MODIFIED_FILES" ]]; then
  echo '{"error":"No modified files found to deliver"}' >&2
  exit 1
fi

# --- Generate slug from title ---

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | \
    sed 's/[^a-z0-9]/-/g' | \
    sed 's/--*/-/g' | \
    sed 's/^-//' | \
    sed 's/-$//' | \
    cut -c1-40
}

SLUG=$(slugify "$TITLE")
BRANCH="feature/${TASK_ID}-${SLUG}"

# --- Phase 1: Branch + commit + push ---

if [[ -z "$PR_BODY_FILE" ]]; then
  # Create branch
  CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
  if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
    git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH" 2>/dev/null || {
      echo "{\"error\":\"Failed to create or switch to branch ${BRANCH}\"}" >&2
      exit 1
    }
  fi

  # Stage files explicitly
  while IFS= read -r file; do
    [[ -z "$file" ]] && continue
    if [[ -f "$file" ]]; then
      git add "$file"
    fi
  done <<< "$MODIFIED_FILES"

  # Build commit message
  local_type="feat"
  if echo "$TITLE" | grep -qiE '(fix|bug|patch|repair|correct)'; then
    local_type="fix"
  elif echo "$TITLE" | grep -qiE '(refactor|cleanup|reorganize)'; then
    local_type="refactor"
  elif echo "$TITLE" | grep -qiE '(doc|readme|comment)'; then
    local_type="docs"
  elif echo "$TITLE" | grep -qiE '(test|spec)'; then
    local_type="test"
  fi

  COMMIT_MSG="${local_type}(${SLUG}): ${TITLE}

Task: ${TASK_ID}
Risk: ${TIER}"

  git commit -m "$COMMIT_MSG" || {
    echo "{\"error\":\"Commit failed\"}" >&2
    exit 1
  }

  # Push branch (skip if no remote configured)
  HAS_REMOTE=false
  if git remote get-url origin &>/dev/null; then
    HAS_REMOTE=true
    git push -u origin "$BRANCH" 2>/dev/null || {
      echo "{\"error\":\"Push failed. Check remote access for origin.\"}" >&2
      exit 1
    }
  fi

  if [[ "$HAS_REMOTE" == "false" ]]; then
    # No remote — commit only, skip PR creation
    jq -n \
      --arg status "DONE" \
      --arg pr_url "" \
      --arg branch "$BRANCH" \
      --arg summary "Committed to ${BRANCH} (no remote configured, skipped push/PR)" \
      '{status:$status, pr_url:$pr_url, branch:$branch, summary:$summary}'
    exit 0
  fi

  # PAUSE: ask LLM to write PR body
  local task_dir="${FORGE_DIR}/pipeline/runs/${TASK_ID}"
  mkdir -p "$task_dir"
  PR_BODY_OUTPUT="${task_dir}/pr-body.md"

  jq -n \
    --arg status "PAUSE" \
    --arg task "write-pr-body" \
    --arg prompt_file "${PROMPTS_DIR}/pr-body-prompt.md" \
    --arg output_file "$PR_BODY_OUTPUT" \
    --arg branch "$BRANCH" \
    --arg resume "bash ${FORGE_DIR}/pipeline/deliver.sh ${TASK_ID} ${PR_BODY_OUTPUT}" \
    --argjson context '["",""]' \
    '{status:$status, task:$task, prompt_file:$prompt_file, output_file:$output_file, branch:$branch, context:$context, resume:$resume}'
  exit 0
fi

# --- Phase 2: Create PR with body ---

if [[ ! -f "$PR_BODY_FILE" ]]; then
  echo "{\"error\":\"PR body file not found: ${PR_BODY_FILE}\"}" >&2
  exit 1
fi

PR_BODY=$(cat "$PR_BODY_FILE")

PR_TITLE="${TITLE}"
if [[ ${#PR_TITLE} -gt 70 ]]; then
  PR_TITLE=$(echo "$PR_TITLE" | cut -c1-67)"..."
fi

# Add risk badge
RISK_BADGE=""
case "$TIER" in
  T1) RISK_BADGE="<!-- risk:T1 --> **Risk: T1** (Low)" ;;
  T2) RISK_BADGE="<!-- risk:T2 --> **Risk: T2** (Moderate)" ;;
  T3) RISK_BADGE="<!-- risk:T3 --> **Risk: T3** (Critical)" ;;
esac

FULL_BODY="${RISK_BADGE}

${PR_BODY}

---
Task: \`${TASK_ID}\`"

PR_URL=$(gh pr create \
  --title "$PR_TITLE" \
  --body "$FULL_BODY" \
  --head "$BRANCH" 2>/dev/null) || {
  echo "{\"error\":\"gh pr create failed. Is gh authenticated?\"}" >&2
  exit 1
}

# Add labels based on tier
case "$TIER" in
  T3) gh pr edit "$PR_URL" --add-label "critical,security-review" 2>/dev/null || true ;;
  T2) gh pr edit "$PR_URL" --add-label "needs-review" 2>/dev/null || true ;;
esac

jq -n \
  --arg pr_url "$PR_URL" \
  --arg branch "$BRANCH" \
  --arg task_id "$TASK_ID" \
  --arg tier "$TIER" \
  '{pr_url:$pr_url, branch:$branch, task_id:$task_id, tier:$tier}'
