#!/usr/bin/env bash
# forge pipeline — verify: run verification checks against task
# Generated by: forge init
set -euo pipefail

FORGE_DIR=".forge"
CONFIG_FILE="${FORGE_DIR}/forge.yaml"

TASK_ID="${1:-}"
TIER="${2:-T1}"

if [[ -z "$TASK_ID" ]]; then
  echo '{"error":"Usage: verify.sh <task-id> <tier>"}' >&2
  exit 1
fi

# --- Config reading ---

read_config() {
  local key="$1"
  local file="$CONFIG_FILE"
  if [[ ! -f "$file" ]]; then
    echo ""
    return
  fi
  if [[ "$key" == *.* ]]; then
    local section="${key%%.*}"
    local subkey="${key#*.}"
    sed -n "/^${section}:/,/^[^ ]/p" "$file" | grep "^  ${subkey}:" | head -1 | sed 's/^[^:]*: *//' | sed 's/^ *"//' | sed 's/" *$//'
  else
    grep "^${key}:" "$file" | head -1 | sed 's/^[^:]*: *//' | sed 's/^ *"//' | sed 's/" *$//'
  fi
}

read_config_bool() {
  local val
  val=$(read_config "$1")
  [[ "$val" == "true" || "$val" == "yes" || "$val" == "1" ]]
}

# --- Check definitions ---

CMD_TYPECHECK="go vet ./..."
CMD_LINT="golangci-lint run"
CMD_TEST="go test ./..."

# Fallbacks if template vars are empty
CMD_TYPECHECK="${CMD_TYPECHECK:-npm run check}"
CMD_LINT="${CMD_LINT:-npm run lint}"
CMD_TEST="${CMD_TEST:-npx vitest run}"

# Optional checks from config
CMD_COVERAGE=$(read_config "commands.coverage")
CMD_SECURITY=$(read_config "commands.security")
CMD_ANTIPATTERN=$(read_config "commands.antipatterns")

ENABLE_COVERAGE=$(read_config "verify.coverage")
ENABLE_SECURITY=$(read_config "verify.security")
ENABLE_ANTIPATTERN=$(read_config "verify.antipatterns")

# --- Run a single check ---

RESULTS=()
PASSED=true
FAILED_CHECK=""
FAILED_STDERR=""

run_check() {
  local name="$1"
  local cmd="$2"
  local required="${3:-true}"

  if [[ -z "$cmd" ]]; then
    RESULTS+=("{\"check\":\"${name}\",\"status\":\"skipped\",\"reason\":\"no command configured\"}")
    return 0
  fi

  local start_time
  start_time=$(date +%s)

  local stderr_file
  stderr_file=$(mktemp)
  local exit_code=0
  eval "$cmd" 2>"$stderr_file" >/dev/null || exit_code=$?

  local end_time
  end_time=$(date +%s)
  local duration=$((end_time - start_time))

  if [[ $exit_code -eq 0 ]]; then
    RESULTS+=("{\"check\":\"${name}\",\"status\":\"passed\",\"duration_s\":${duration}}")
    rm -f "$stderr_file"
    return 0
  else
    local stderr_content
    stderr_content=$(cat "$stderr_file" | head -50 | jq -Rs .)
    rm -f "$stderr_file"

    RESULTS+=("{\"check\":\"${name}\",\"status\":\"failed\",\"exit_code\":${exit_code},\"duration_s\":${duration},\"stderr\":${stderr_content}}")

    if [[ "$required" == "true" ]]; then
      PASSED=false
      FAILED_CHECK="$name"
      FAILED_STDERR=$(echo "$stderr_content" | jq -r .)
      return 1
    fi
    return 0
  fi
}

# --- Execute checks sequentially ---

# 1. Typecheck (always required)
run_check "typecheck" "$CMD_TYPECHECK" "true" || true

# 2. Lint (always required)
if [[ "$PASSED" == "true" ]]; then
  run_check "lint" "$CMD_LINT" "true" || true
fi

# 3. Tests (always required)
if [[ "$PASSED" == "true" ]]; then
  run_check "test" "$CMD_TEST" "true" || true
fi

# 4. Coverage (optional, T2+ only)
if [[ "$PASSED" == "true" && "$ENABLE_COVERAGE" == "true" && ("$TIER" == "T2" || "$TIER" == "T3") ]]; then
  run_check "coverage" "$CMD_COVERAGE" "false" || true
fi

# 5. Security scan (optional, T3 only)
if [[ "$PASSED" == "true" && "$ENABLE_SECURITY" == "true" && "$TIER" == "T3" ]]; then
  run_check "security" "$CMD_SECURITY" "true" || true
fi

# 6. Anti-pattern check (optional)
if [[ "$PASSED" == "true" && "$ENABLE_ANTIPATTERN" == "true" ]]; then
  run_check "antipatterns" "$CMD_ANTIPATTERN" "false" || true
fi

# 7. Browser smoke tests (enabled by default for frontend changes)
ENABLE_BROWSER=$(read_config "verification.browser.enabled")
CMD_BROWSER=$(read_config "verification.browser.command")
CMD_BROWSER="${CMD_BROWSER:-bash .forge/pipeline/browser-smoke.sh}"

if [[ "$PASSED" == "true" && "$ENABLE_BROWSER" == "true" ]]; then
  # Only run browser tests if frontend files were modified
  HAS_FRONTEND_CHANGES=false
  if git diff --name-only HEAD~1 2>/dev/null | grep -qE '\.(tsx|jsx|svelte|vue|css|scss|html)$|/routes/|/pages/|/components/|/app/'; then
    HAS_FRONTEND_CHANGES=true
  fi

  if [[ "$HAS_FRONTEND_CHANGES" == "true" ]]; then
    run_check "browser" "$CMD_BROWSER" "false" || true
  else
    RESULTS+=("{\"check\":\"browser\",\"status\":\"skipped\",\"reason\":\"no frontend files changed\"}")
  fi
fi

# --- Build results JSON ---

RESULTS_JSON=$(printf '%s\n' "${RESULTS[@]}" | jq -s '.')

if [[ "$PASSED" == "true" ]]; then
  jq -n \
    --argjson passed true \
    --argjson checks "$RESULTS_JSON" \
    --arg tier "$TIER" \
    '{passed:$passed, tier:$tier, checks:$checks}'
else

  jq -n \
    --argjson passed false \
    --arg failed_check "$FAILED_CHECK" \
    --arg stderr "$FAILED_STDERR" \
    --argjson checks "$RESULTS_JSON" \
    --arg tier "$TIER" \
    '{passed:$passed, failed_check:$failed_check, stderr:$stderr, tier:$tier, checks:$checks}'
fi
