package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/samahlstrom/forge-cli/internal/resolve"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

func init() {
	cmd := &cobra.Command{
		Use:   "roster",
		Short: "Generate agent roster manifest from frontmatter",
		RunE:  runRoster,
	}
	rootCmd.AddCommand(cmd)
}

type agentFrontmatter struct {
	ID          string `yaml:"id"`
	Name        string `yaml:"name"`
	Type        string `yaml:"type"`
	Specializes string `yaml:"specializes"`
	GoodAt      string `yaml:"good_at"`
	Files       string `yaml:"files"`
}

type rosterFile struct {
	Agents []agentFrontmatter `yaml:"agents"`
}

func runRoster(_ *cobra.Command, _ []string) error {
	cwd, _ := os.Getwd()

	// Use resolve package to find agents from both global and local
	agentInfos := resolve.ListAgents(cwd)
	if len(agentInfos) == 0 {
		return fmt.Errorf("no agents found — run forge setup or forge init first")
	}

	var agents []agentFrontmatter
	for _, info := range agentInfos {
		content, err := os.ReadFile(info.Path)
		if err != nil {
			continue
		}
		fm := extractFrontmatter(string(content))
		if fm != nil {
			agents = append(agents, *fm)
		}
	}

	if len(agents) == 0 {
		return fmt.Errorf("no agents with frontmatter found")
	}

	roster := rosterFile{Agents: agents}
	out, err := yaml.Marshal(roster)
	if err != nil {
		return fmt.Errorf("failed to marshal roster: %w", err)
	}

	header := "# Auto-generated by: forge roster\n# Do not edit — regenerate with: forge roster\n\n"
	rosterPath := filepath.Join(resolve.ForgeHome(), "agents", "roster.yaml")
	if err := os.WriteFile(rosterPath, []byte(header+string(out)), 0o644); err != nil {
		return fmt.Errorf("failed to write roster: %w", err)
	}

	fmt.Printf("Roster generated: %s (%d agents)\n", rosterPath, len(agents))
	return nil
}

func extractFrontmatter(content string) *agentFrontmatter {
	if !strings.HasPrefix(strings.TrimSpace(content), "---") {
		return nil
	}

	// Find the closing ---
	trimmed := strings.TrimSpace(content)
	rest := trimmed[3:] // skip opening ---
	idx := strings.Index(rest, "\n---")
	if idx < 0 {
		return nil
	}

	fmContent := rest[:idx]
	var fm agentFrontmatter
	if err := yaml.Unmarshal([]byte(fmContent), &fm); err != nil {
		return nil
	}

	if fm.ID == "" {
		return nil
	}

	return &fm
}

func generateRoster(cwd string) error {
	agentInfos := resolve.ListAgents(cwd)
	if len(agentInfos) == 0 {
		return nil
	}

	var agents []agentFrontmatter
	for _, info := range agentInfos {
		content, err := os.ReadFile(info.Path)
		if err != nil {
			continue
		}
		fm := extractFrontmatter(string(content))
		if fm != nil {
			agents = append(agents, *fm)
		}
	}

	if len(agents) == 0 {
		return nil
	}

	roster := rosterFile{Agents: agents}
	out, err := yaml.Marshal(roster)
	if err != nil {
		return err
	}

	header := "# Auto-generated by: forge roster\n# Do not edit — regenerate with: forge roster\n\n"
	rosterPath := filepath.Join(resolve.ForgeHome(), "agents", "roster.yaml")
	return os.WriteFile(rosterPath, []byte(header+string(out)), 0o644)
}
