#!/usr/bin/env bash
# forge pipeline — deliver: branch, commit, push
# Generated by: forge init
# PR creation is handled by the SKILL.md orchestrator, not this script.
set -euo pipefail

FORGE_DIR=".forge"
FORGE_GLOBAL="${FORGE_GLOBAL:-$HOME/.forge}"
source "${FORGE_GLOBAL}/pipeline/helpers.sh"

TASK_ID="${1:-}"

if [[ -z "$TASK_ID" ]]; then
  echo '{"error":"Usage: deliver.sh <task-id>"}' >&2
  exit 1
fi

# --- Read task state from bd ---

TASK_JSON=$(bd show "$TASK_ID" --json 2>/dev/null)

TITLE=$(echo "$TASK_JSON" | jq -r 'if type == "array" then .[0].title else .title end // "untitled"')
TIER=$(bd_get_label "$TASK_ID" "tier")
TIER="${TIER:-T1}"

# Detect modified files from git
MODIFIED_FILES=$(git diff --name-only HEAD 2>/dev/null || true)
if [[ -z "$MODIFIED_FILES" ]]; then
  MODIFIED_FILES=$(git diff --cached --name-only 2>/dev/null || true)
fi
if [[ -z "$MODIFIED_FILES" ]]; then
  MODIFIED_FILES=$(git status --porcelain | grep -v '^\?' | awk '{print $2}')
fi

if [[ -z "$MODIFIED_FILES" ]]; then
  echo '{"error":"No modified files found to deliver"}' >&2
  exit 1
fi

# --- Generate branch name ---

SLUG=$(slugify "$TITLE")
BRANCH="feature/${TASK_ID}-${SLUG}"

# --- Branch + commit + push ---

CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
  git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH" 2>/dev/null || {
    echo "{\"error\":\"Failed to create or switch to branch ${BRANCH}\"}" >&2
    exit 1
  }
fi

# Stage modified files
while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  if [[ -f "$file" ]]; then
    git add "$file"
  fi
done <<< "$MODIFIED_FILES"

# Build commit message
COMMIT_TYPE="feat"
if echo "$TITLE" | grep -qiE '(fix|bug|patch|repair|correct)'; then
  COMMIT_TYPE="fix"
elif echo "$TITLE" | grep -qiE '(refactor|cleanup|reorganize)'; then
  COMMIT_TYPE="refactor"
elif echo "$TITLE" | grep -qiE '(doc|readme|comment)'; then
  COMMIT_TYPE="docs"
elif echo "$TITLE" | grep -qiE '(test|spec)'; then
  COMMIT_TYPE="test"
fi

COMMIT_MSG="${COMMIT_TYPE}(${SLUG}): ${TITLE}

Task: ${TASK_ID}
Risk: ${TIER}"

COMMIT_SHA=""
git commit -m "$COMMIT_MSG" && COMMIT_SHA=$(git rev-parse HEAD) || {
  echo '{"error":"Commit failed"}' >&2
  exit 1
}

# Push branch (skip if no remote)
HAS_REMOTE=false
if git remote get-url origin &>/dev/null; then
  HAS_REMOTE=true
  git push -u origin "$BRANCH" 2>/dev/null || {
    echo '{"error":"Push failed. Check remote access for origin."}' >&2
    exit 1
  }
fi

# --- Output result ---

jq -n \
  --arg branch "$BRANCH" \
  --arg commit_sha "$COMMIT_SHA" \
  --arg task_id "$TASK_ID" \
  --arg tier "$TIER" \
  --argjson has_remote "$HAS_REMOTE" \
  '{branch:$branch, commit_sha:$commit_sha, task_id:$task_id, tier:$tier, has_remote:$has_remote}'
